# Generated by Django 4.1 on 2022-08-24 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('avatar', models.ImageField(blank=True, upload_to='driver/avatars/', verbose_name='Фото')),
                ('transport', models.CharField(choices=[('CAR', 'Машина'), ('SCOOTER', 'Скутер'), ('BICYCLE', 'Велосипед'), ('HELICOPTER', 'Вертолет?'), ('BOAT', 'Лодка?'), ('WALK', 'Пешком')], default='WALK', help_text='Обязательное поле', max_length=50, verbose_name='Вид транспорта')),
                ('plate_number', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль курьера')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('avatar', models.ImageField(blank=True, upload_to='customer/avatars/', verbose_name='Фото')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль клиента')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
